[package]
name = "rustfm"
version = "0.1.0"
authors = [ "Nathaniel Ledford <nate@nateledford.com>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
clap = "3.0.0-beta.2"
reqwest = { version = "0.10", features = [ "json" ] }
serde = "1.0.116"
serde_json = "1.0.57"
thiserror = "1.0.20"
tokio = { version = "0.2", features = [ "full" ] }
