[package]
name = "rustfm-scraper"
version = "0.1.0" #:version
authors = [ "Nathaniel Ledford <nate@nateledford.com>" ]
description = "Scrapes listening history from Last.fm and stores it in a file"
repository = "https://github.com/nledford/rustfm-scraper"
keywords = [ "lastfm", "last-fm", "api" ]
license = "MIT"
categories = [ "api-bindings", "multimedia" ]
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0.32"
async-recursion = "0.3.1"
chrono = { version = "0.4.15", features = [ "serde" ] }
clap = "3.0.0-beta.2"
crossbeam = "0.7.3"
csv = "1.1.3"
dirs = "3.0.1"
futures = "0.3.5"
indicatif = "0.15.0"
libmath = "0.2.1"
reqwest = { version = "0.10.8", features = [ "json" ] }
serde = { version = "1.0.116", features = [ "derive" ] }
serde_json = "1.0.57"
thiserror = "1.0.20"
tokio = { version = "0.2.22", features = [ "full" ] }
