[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

# Sort dependencies in `Cargo.toml`
[tasks.sort]
install_crate = "cargo-sort-ck"
command = "cargo-sort-ck"
args = ["-w"]

# Installs application on local computer
[tasks.install]
command = "cargo"
args = ["install","--path","."]

# publishes application to Crates.io
[tasks.publish]
command = "cargo"
args = "publish"

# Runs application using development build
[tasks.run]
command = "cargo"
args = ["run","--","fetch"]